import { colorVars } from "./theme.js";
import type { ResolvedTheme } from "./types.js";
import { buildVocabulary } from "./vocabulary.js";

const RESET = `*, *::before, *::after { box-sizing: border-box; }
* { margin: 0; }
html { -webkit-text-size-adjust: 100%; }
body {
  background: var(--in-bg); color: var(--in-text);
  font-family: var(--in-font-ui); font-size: var(--in-text-body);
  line-height: 1.55; min-height: 100svh; -webkit-font-smoothing: antialiased;
}
h1, h2, h3, h4, h5, h6, p { overflow-wrap: break-word; }
img, picture, video, canvas, svg { display: block; max-width: 100%; }
input, button, textarea, select { font: inherit; color: inherit; }
a { color: var(--in-brand); text-underline-offset: 0.15em; text-decoration-thickness: 1px; }
a:hover { color: var(--in-brand-hover); }
code, kbd, samp, pre { font-family: var(--in-font-mono); font-size: 0.925em; }
hr { border: 0; border-top: 1px solid var(--in-line); }
:focus-visible { outline: 2px solid var(--in-brand); outline-offset: 2px; }
::selection { background: var(--in-brand-soft); color: var(--in-on-brand-soft); }
@media (prefers-reduced-motion: reduce) {
  *, *::before, *::after {
    animation-duration: 0.01ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0.01ms !important;
    scroll-behavior: auto !important;
  }
}`;

/**
 * Generate the stylesheet: reset + tokens + the roles in use.
 * Modern CSS only: cascade layers, light-dark(), OKLCH, container queries.
 */
export function generateCss(theme: ResolvedTheme, used: Set<string> | "all", version: string): string {
  const vocab = buildVocabulary({ collapse: theme.collapse });
  const roles = used === "all" ? vocab : vocab.filter((role) => used.has(role.name));

  const tokens: string[] = ["  color-scheme: light dark;"];
  for (const [name, value] of Object.entries(colorVars(theme))) tokens.push(`  ${name}: ${value};`);
  for (const [name, value] of Object.entries(theme.vars)) tokens.push(`  ${name}: ${value};`);

  const roleCss: string[] = [];
  const extras = new Set<string>();
  for (const role of roles) {
    if (role.css.trim().length > 0) roleCss.push(role.css);
    if (role.extra) extras.add(role.extra);
  }

  return `/* Generated by Intent v${version} (intent-css) — https://github.com/dataswarmproject/intent-css
 * Semantic roles, relationship spacing, OKLCH theming. Do not edit by hand: run \`intent build\`.
 * Emitted: ${used === "all" ? "full vocabulary" : `${roles.length} roles in use`}. */

@layer intent.reset, intent.tokens, intent.roles;

@layer intent.reset {
${RESET}
}

@layer intent.tokens {
:root {
${tokens.join("\n")}
}
}

@layer intent.roles {
${[...roleCss, ...extras].join("\n\n")}
}
`;
}
